import React from 'react'

export default function ProductiveItemsOptions() {
  return (
    <>

      <option value="soya-souce">Soya Souce</option>
      <option value="fanail-bottle">Fanail Bottle</option>
      <option value="cooking-oil">Cooking Oil</option>
      <option value="china-salt">China Salt</option>
      <option value="ghee">ghee</option>
      <option value="pine-apple">PineApple</option>
      <option value="mashroom">Mashroom</option>
      <option value="egg">Egg</option>
      <option value="mayoniz">Mayoniz</option>
      <option value="baryani-masala">Baryani Masala</option>
      <option value="qorma-masala">Qorma Masala</option>
      <option value="tea-pati">Tea Pati</option>
      <option value="mix-fruit">Mix Fruit</option>
      <option value="sweet-corn">Sweet Corn</option>
      <option value="roti-lifafa-khaki">Roti Lifafa</option>
      <option value="custard-powdr">Custard Powdr(1.200gm)</option>
      <option value="jaly-sabz">Jaly Sabz(2.500gm)</option>
      <option value="kheer-mix">Kheer Mix(155gm)</option>
      <option value="stobry-souce-bottle">Stobry Souce Bottle(623gm)</option>
      <option value="chocklet-souce-botle">Chocklet Souce Botle(680)</option>
      <option value="knoor-cubs">Knoor Cubs</option>
      <option value="nido-milk">Nido Milk</option>
      <option value="machas">Machas</option>
      <option value="barten-soap">Barten Soap</option>
      <option value="food-color-green">Food Color Green(500mg)</option>
      <option value="achar-masala">Achar Masala</option>
      <option value="milk-pack">Milk Pack(250ml)</option>
      <option value="milk-pack-cream">Milk Pack Cream</option>
      <option value="soap-hand-wash">Soap Hand Wash</option>
      <option value="kastik-soda">Kastik Soda</option>
      <option value="mitha-soda">Mitha Soda</option>
      <option value="kalwanji">Kalwanji</option>
      <option value="white-paper">White Paper</option>
      <option value="mineral-water">Mineral Water(pet)</option>
      <option value="mineral-water1">Mineral Water(1.5)(pet)</option>
      <option value="mineral-water2">Mineral Water(2.5)(pet)</option>
      <option value="mineral-water3">Mineral Water(500ML)(pet)</option>
      <option value="kala-zeera">Kala Zeera</option>
      <option value="tissue-boxes">Tissue Boxes</option>
      <option value="cherry">Cherry</option>
      <option value="soghi">Soghi</option>
      <option value="alo-bukhara">Alo Bukhara</option>
      <option value="maida">Maida</option>
      <option value="sugar">Sugar</option>
      <option value="safaid-chana">Safaid Chana</option>
      <option value="every-day-milk">Every Day Milk</option>
      <option value="anar-dana">Anar Dana</option>
      <option value="qasoori-mathi">Qasoori Mathi</option>
      <option value="long-sabit">Long Sabit</option>
      <option value="Sabaz-alayechi">Sabaz Alayechi</option>
      <option value="jaifal">Jaifal</option>
      <option value="bari-alayechi">BAri Alayechi</option>
      <option value="jalwatri">Jalwatri</option>
      <option value="lobiyah-surkh">Lobiyah Surkh</option>
      <option value="badam">Badam</option>
      <option value="haldi">Haldi</option>
      <option value="lal-mirch">Lal Mirch</option>
      <option value="qandri-mirch">Qandri Mirch</option>
      <option value="safaid-till">Safaid Till</option>
      <option value="daal-chana">Daal Chana</option>
      <option value="bassen">Bassen</option>
      <option value="saraf">Saraf</option>
      <option value="shoper">Shoper</option>
      <option value="daar-chini">Daar Chini</option>
      <option value="khushk-dhaniya">Khushk Dhaniya</option>
      <option value="white-zeera">White Zeera</option>
      <option value="imlee">Imlee</option>
      <option value="salt">Salt</option>
      <option value="daal-mash">Daal Mash</option>
      <option value="corn-floor">Corn Floor</option>
      <option value="lehsan">Lehsan</option>
      <option value="hari-mirch">Hari Mirch</option>
      <option value="new-potato">New Potato</option>
      <option value="purane-alo">Purane Alo</option>
      <option value="gajar">Gajar</option>
      <option value="adhark">Adhrak</option>
      <option value="piyan">Piyaz</option>
      <option value="sabaz-piyaz">Sabaz Piyaz</option>
      <option value="tomato">Tomato</option>
      <option value="bleach">Bleach 1.5L</option>
      <option value="sella-rice">Sella Rice</option>
      <option value="baspati-rice">Baspati Rice</option>
      <option value="shopr-pizza">Shopr Pizza</option>
      <option value="praima-powdr">Praima Powder</option>
      <option value="chilli-souce">Chilli Souce</option>
      <option value="leshan-powdr">Leshan Powder</option>
      <option value="khashkhash">Khashkhash</option>
      <option value="sonf">Sonf</option>
      <option value="murghi-masala">Murghi Masala(100gm)</option>
      <option value="adhrak-powdr">Adhark Powder(50gm)</option>
      <option value="ketchup">Ketchup</option>
      <option value="tooth-pick">Tooth Pick</option>
      <option value="coke-reg">Coke Reg(pet)</option>
      <option value="coke-1.5">Coke 1.5L(pet)</option>
      <option value="coke-2.15">Coke 2.15L(pet)</option>
      <option value="coke-sugerf">Coke Zero SGR Can 259ML(pet)</option>
      <option value="teen-pack">Teen Pack(pet)</option>
      <option value="custard">Custard</option>
      <option value="podene">Podena</option>
      <option value="garam-masala">Garam Masala</option>
      <option value="kachri">Kachri</option>
      <option value="coconat-powdr">Coconat Powder</option>
      <option value="national-salt">National Salt</option>
      <option value="gol-mirch-sabit">Gol Mirch Sabit</option>
      <option value="mathi-dana">Mathi Dana</option>
      <option value="baking-powdr">Baching Powder</option>
      <option value="cheese">Cheese</option>
      <option value="matar">Matar</option>
      <option value="achar">Achar</option>
      <option value="surf">Surf</option>
      <option value="makhan">Makhan</option>
      <option value="khoya">Khoya</option>
      <option value="white-sirka">White Sirka</option>
      <option value="desi-ghee">Desi Ghee</option>
      <option value="chilli-souce">Chilli Souce (4L)</option>
      <option value="pista">Pista</option>
      <option value="kajo">Kajo</option>
      <option value="tatri">Tatri</option>
      <option value="chat-masala">Chat Masala</option>
      <option value="green-tea">Green Tea</option>
      <option value="mutton">Mutton</option>
      <option value="chicken">Chicken</option>
      <option value="dahi">Dahi</option>
      <option value="milk">Milk</option>
      <option value="khera">Khera</option>
      <option value="sagu-dana">Sagu Dana</option>
      <option value="lemon">Lemon</option>
      <option value="shimlah-mirch">Shimla Mirch</option>
      <option value="kajo">Kajo</option>
      <option value="haldi-sabit">Haldi Sabit</option>
      <option value="band-ghobi">Band Ghobi</option>
      <option value="palak">Palak</option>
      <option value="broost-masala">Brost Masala</option>
      <option value="bhindi">Bhindi</option>
      <option value="brown-sirka">Brown Sirka</option>
      <option value="moli">Moli</option>
      <option value="nestle-cream">Nestle Cream</option>
      <option value="apple">Apple</option>
      <option value="banana">Banana</option>
      <option value="chicken-boon-less">Chicken Boonless</option>
      <option value="corn-flex">Corn Flex</option>
      <option value="fish">Fish</option>
      <option value="charbi">Charbi</option>
      <option value="respi-masala">Respi Masala</option>
      <option value="khameer">Khameer</option>
      <option value="marhaba-ashrafi">Marhaba Ashrafi</option>
      <option value="kheer-mix">Kheer Mix</option>
      <option value="fily-kilr">Fily Kilr</option>
      <option value="karahi-ghost-masala">Karahi Ghost Masala</option>
      <option value="sawaiyan-rangeen">Sawaiyan Rangeen</option>
      <option value="ketchup-balti">Ketchup Balti</option>
      <option value="lobiya-white">Lobiya White</option>
      <option value="beef">Beef</option>
      <option value="american-badam">American Badam</option>
      <option value="sandal">Sandal</option>
      <option value="fresh-cream">Fresh Cream</option>
      <option value="baraf">Baraf</option>
      <option value="daal-mong">Daal Mong</option>
      <option value="daal-masoor">Daal Masoor</option>
      <option value="salad-pata">Salad Pata</option>
      <option value="chokandr">Chohkander</option>
      <option value="desi-murgh">Desi Murgh</option>
      <option value="fruit-cake">Fruit Cake</option>
      <option value="bleach">Bleach (1L)</option>
      <option value="pista">Pista Kita</option>
      <option value="milk-pack">Milk Pack</option>
      <option value="nido-milk">Nido Milk</option>
      <option value="wings">Wings</option>
      <option value="Gajr Halwa">Gajr Halwa</option>
      <option value="knorr-cubs">Knorr Cubs</option>
      <option value="phool-ghobi">Phool Ghobi</option>
      <option value="nido-bunyad">Nido Bunyad</option>
      <option value="maethi">Maethi</option>
      <option value="tapal-tea">Tapal Tea</option>
      <option value="gulab-jamun">Gulab Jamun</option>
      <option value="sabat-dhania">Sabat Dhania</option>
      <option value="nodalz">Nodalz</option>
      <option value="rice">Rice</option>
      <option value="zeera-safaid">Zeera Safaid</option>
      <option value="burger-bun">Burger Bun</option>
      <option value="chicken-piece">Chicken Piece</option>
      <option value="paratha">Paratha</option>
      <option value="ketchup-sache">Ketchup Sashe</option>
      <option value="bread-shawarma">Bread Shawarma</option>
      <option value="shawarma-souce">Shawarma Souce</option>
      <option value="est">Eest</option>
      <option value="baking-powder">Backing Powder</option>
      <option value="egg-powder">Egg Powder</option>
      <option value="ataa">Ataa</option>
      <option value="ice-cream">Ice Cream</option>
      <option value="coffe">Coffe</option>
      <option value="sabaz-dhaniya">Sabaz Dhaniya</option>
      <option value="speggtise">Speggtise</option>
      <option value="Kali-Mirch">Kali Mirch</option>
      <option value="chicken-wings">Chicken Wings</option>
      <option value="white-mirch">White Mirch</option>
      <option value="fries">fries</option>
      <option value="masala-chat">Chat Masala</option>
      <option value="safi-chicken">Safi Chicken</option>
      <option value="aroo">Aroo</option>
      <option value="saib-maraba">Saib Maraba</option>
      <option value="amrood">Amrood</option>
      <option value="phalian">Phalian</option>
      <option value="chicken-peti">Chicken Peti</option>
      <option value="malai-boti">Malai Boti</option>
      <option value="bbq">BBQ</option>
      <option value="khopra">Khopra</option>
      <option value="roti">Roti</option>
      <option value="russ">Russ</option>
      <option value="coke-diet">Coke Diet</option>
      <option value="black-olive">Black Olive</option>
      <option value="satra">Satra</option>
      <option value="chilli-Garlic">Chilli Garlic</option>
      <option value="chicken-paproni">Chicken Paproni</option>
      <option value="nigets">Nigets</option>
      <option value="eka-powder">Eka Powder</option>
      <option value="spark-tea">Spark Tea</option>
      <option value="giri-brada">Giri Brada</option>
      <option value="chicken-sosojis">Chicken Sos</option>
      <option value="strabery">Strabery</option>
      <option value="bangen">Bangen</option>
      <option value="tende">Tende</option>
      <option value="krelay">karely</option>
      <option value="barf">Barf</option>
      <option value="chicken-powdr">Chicken Powder</option>
      <option value="our-gheenu">Our Gheenu</option>
      <option value="pizza-pest">Pizza Pest</option>
      <option value="eiko-powder">Eiko Powder</option>
      <option value="pizza-souce">Pizza Souce</option>
      <option value="black-salt">Black Salt</option>
      <option value="lemon-jouce">Lemon Juice</option>
      <option value="tanger-foods">Tanger Foods</option>
      <option value="sogi">Sogi</option>
      <option value="milk-coconut-powdr">Milk Coconut Powder</option>
      <option value="paprika-powdr">Paprika POwder</option>
      <option value="italian-tomoto-paste">Italian Tomoato Paste</option>
      <option value="glutton-powder">Glutton Powder</option>
      <option value="worcesters-sauce">Worcesters Souce</option>
      <option value="mustard-paste">Mustard Paste</option>
      <option value="fish-masala">Fish Masala</option>
      <option value="tandoori-masala">Tandori Masala</option>
      <option value="tikka-masala">Tikka Masala</option>
      <option value="garlic-paste">Garlic Paste</option>
      <option value="Tomaoto Paste Laue">Tomato Paste Laue</option>
      <option value="hp-sauce">H.P Sauce</option>
      <option value="chuk">Chuk</option>
      <option value="pratha-bread">Paratha Bread</option>
      <option value="bread-crums">Bread Crums</option>
      <option value="nestle-tea">Nestle Tea</option>
      <option value="khajoor">Khajoor</option>
      <option value="jame-sheeren">Jame Sheeren</option>
      <option value="drink-mango">Drink Mango</option>
      <option value="Nestle-juice">Nestle Juice</option>
      <option value="churri">Churri</option>


    </>
  )
}
